### ISSUE TITLE
Firefox doesn't support insertAdjacentElement()

### ISSUE THREAD

**Issue by leftiness** [geut/mithril-transition#2]
**Source**

``` js
parentNode
  .insertAdjacentElement('beforeend', lastElem);
```

[link](https://github.com/geut/mithril-transition/blob/master/src/index.js#L89)

**Problem**

`insertAdjacentElement()` is apparently something that Mozilla doesn't like.

[link](http://quirksmode.org/dom/html/#t02) [link](http://quirksmode.org/dom/html/innerHTML.html)

**Solution?**

All browsers apparently like `insertBefore()`. What do you think?

[link](http://quirksmode.org/dom/core/#t92) [link](http://quirksmode.org/dom/core/nodeManipulation.html) [link](https://plnkr.co/edit/YI2guLSfQkoRKkGP8VLa)

**Comment by tinchoz49** [comment]
hi @leftiness ! thanks for your report. I replace it with insertAdjacentHTML since has a good perfomance.

Please, test the fix and let me know if everthing is ok.

**Comment by leftiness** [comment]
@tinchoz49 The fix is confirmed. While testing that, I thought that I'd try it out in other browsers, too. I'll open another issue.

**Comment by tinchoz49** [comment]
ahh ok thanks!
